namespace SmartBooks.Domains.Entities
{
    public class CompanyDefaults : AppBaseEntity
    {
        public int DefaultCurrency { get; set; }
        /// <summary>
        /// To allow for users not to enforce account numbers
        /// </summary>
        public bool UseAccountNumbers { get; set; }
        /// <summary>
        /// When true select all from ledgeraccounts table (charts of accounts)
        /// else select accounts not used in parentid column
        /// </summary>
        public bool AllowPostingToParentAccount { get; set; }
        /// <summary>
        /// If inventory module is enabled
        /// else offer a way to create items with basic fields only to enable adding to transactions.
        /// </summary>
        public bool EnableInventoryTracking { get; set; }
        public int DefaultWarehouse { get; set; }
        /// <summary>
        /// If company has multiple warehouses enable selecting
        /// warehouse when entering transactions
        /// </summary>
        public bool HasMultipleWarehouses { get; set; }
        /// <summary>
        /// Gives user a mechanism to prevent transactions falling outside a period
        /// And a way to close books
        /// </summary>
        public bool UseFinancialYear { get; set; }
        public int CurrentFinancialYear { get; set; }
        /// <summary>
        /// We need codes fro importation of data
        /// When auto generated by the system should have this length
        /// </summary>
        public int DefaultCodeLength { get; set; }
    }
}
