using System.ComponentModel.DataAnnotations;

namespace SmartBooks.Domains.Entities
{
    public class UomConversion : AppBaseEntity
    {
        /// <summary>
        /// This is the smaller unit, a multiple of these make the unit to
        /// </summary>
        public int UnitofMeasureFromId { get; set; }
        /// <summary>
        /// This is the bigger unit
        /// </summary>
        public int UnitofMeasureToId { get; set; }
        /// <summary>
        /// A description that is generated by the system
        /// </summary>
        [StringLength(150)]
        public string Description { get; set; }
        /// <summary>
        /// This the number of times the unit from gets into unit to
        /// </summary>
        public decimal Factor { get; set; }
        public UnitofMeasure UnitofMeasureFrom { get; set; }
        public UnitofMeasure UnitofMeasureTo { get; set; }
    }
}
